config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :events

  root to: 'pages#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/vk_signin' => 'sessions#vkontakte', :as => :vk_signin
  get '/fb_signin' => 'sessions#facebook', :as => :fb_signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  validates_uniqueness_of :runner_id
  after_create :make_fb_post

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  scope :fb_identity, ->(){where('provider = ?', 'facebook')}
  scope :vk_identity, ->(){where('provider =?', 'vkontakte')}

  class << self
    def find_with_omniauth(auth)
      find_by(uid: auth['uid'], provider: auth['provider'])
    end

    def create_with_omniauth(auth)
      create! do |identity|
        identity.uid = auth['uid']
        identity.provider = auth['provider']
        identity.oauth_token = auth.credentials.token
        identity.oauth_expires_at = Time.at(auth.credentials.expires_at)
      end
    end
  end

  def has_any_user?
    !self.user.nil?
  end

  def create_user (attrs = {})
    self.create_user!(attrs)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :identities, dependent: :destroy

  def fb_oauth_token
    identities.fb_identity.first.oauth_token
  end

  def vk_oauth_token
    identities.vk_identity.first.oauth_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      !!current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include SocialNetwork

  def index
  end

  def create
    if user_signed_in?
      if session[:signed_in_with] === 'facebook'
        fb_token = current_user.fb_oauth_token
        fb = FB.new(fb_token)
        fb.make_fb_post(params[:runner_id])
      elsif session[:signed_in_with] === 'vkontakte'
        vk_token = current_user.vk_oauth_token
        vk = VK.new(vk_token)
        vk.make_vk_post(params[:runner_id])
      end
    else
      redirect_to root_url, notice: "You need to sign in before continue"
    end
  end

  private

  def event_params
    params.require(:event).permit(:runner_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def facebook
    redirect_to '/auth/facebook'
  end

  def vkontakte
    redirect_to '/auth/vkontakte'
  end

  def create
    auth = request.env["omniauth.auth"]
    identity = Identity.find_with_omniauth(auth)
    if identity.nil?
      identity = Identity.create_with_omniauth(auth)
    end
    reset_session
    if identity.user.present?
      session[:user_id] = identity.user_id
      session[:signed_in_with] = identity.provider
      redirect_to events_url, :notice => 'Signed in!'
    else
      if auth['info']
        user_name = auth['info']['name'] || ""
        identity.create_user(name: user_name)
        identity.save
      end
      session[:user_id] = identity.user_id
      session[:signed_in_with] = identity.provider
      redirect_to events_url, notice: 'Linked your account and Signed in!'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/create.js.erb
$('.messages').after("<div class='alert alert-success'>" + 'Successfully posted to your account wall' + "<button class='close' aria-hidden='true' data-dismiss='alert' type='button'>x</button></div>");

app/views/events/index.html.haml
.row.row-centered
  %h3 Please enter your runner id
  .col-md-12
    = form_tag  events_path, method: :post, class: 'form-inline', remote: true do
      = text_field_tag :runner_id, class: 'form-control'
      = submit_tag 'Post video by runner id', class: 'btn btn-primary'

app/views/layouts/_content.html.haml
.content  
  %form.form-horizontal
    %fieldset
      .form-group
        %label.col-lg-2.control-label{:for => "inputEmail"} Email
        .col-lg-10
          %input#inputEmail.form-control{:placeholder => "Email", :type => "text"}/
      .form-group
        %label.col-lg-2.control-label{:for => "inputPassword"} Password
        .col-lg-10
          %input#inputPassword.form-control{:placeholder => "Password", :type => "password"}/
          .checkbox
            %label
              %input{:type => "checkbox"}/
              Remember me
      .form-group
        .col-lg-10.col-lg-offset-2
          %button.btn.btn-primary{:type => "reset"} Cancel
          %button.btn.btn-success{:type => "submit"} Submit
        .share
          %li  
            %a.btn.btn-block.btn-social.btn-facebook{:href => "/fb_signin"}
              %i.fa.fa-facebook
              Sign in with Fb
          %li
            %a.btn.btn-block.btn-social.btn-vk{:href => "/vk_signin"}
              %i.fa.fa-vk
              Sign in with Vk

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
%div{:class => "messages"}
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
        = content_tag :div, msg, :id => "flash_#{name}"
  %h1 Some messages here

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li= link_to 'Sign out', signout_path
- else
  %li= link_to 'Sign in with facebook', fb_signin_path
  %li= link_to 'Signin with VK', vk_signin_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Fb Wall Post'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Fb Wall Post'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
      / = console
    = render 'layouts/content'